[2024-06-28T00:10:49.809+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T00:10:49.819+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_load_to_s3 manual__2024-06-28T00:10:43.659885+00:00 [queued]>
[2024-06-28T00:10:49.825+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_load_to_s3 manual__2024-06-28T00:10:43.659885+00:00 [queued]>
[2024-06-28T00:10:49.825+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T00:10:49.840+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): tsk_load_to_s3> on 2024-06-28 00:10:43.659885+00:00
[2024-06-28T00:10:49.845+0000] {standard_task_runner.py:63} INFO - Started process 6239 to run task
[2024-06-28T00:10:49.848+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_load_to_s3', 'manual__2024-06-28T00:10:43.659885+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/zillowanalytics.py', '--cfg-path', '/tmp/tmpb9e3kt6n']
[2024-06-28T00:10:49.849+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask tsk_load_to_s3
[2024-06-28T00:10:49.884+0000] {task_command.py:426} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_load_to_s3 manual__2024-06-28T00:10:43.659885+00:00 [running]> on host ip-172-31-6-214.us-east-2.compute.internal
[2024-06-28T00:10:49.958+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T00:10:43.659885+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T00:10:43.659885+00:00'
[2024-06-28T00:10:49.958+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T00:10:49.971+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-28T00:10:49.972+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'aws s3 mv /home/ubuntu/response_data_28062024001046.json s3://zillow-etl-bucket/']
[2024-06-28T00:10:49.980+0000] {subprocess.py:86} INFO - Output:
[2024-06-28T00:10:50.790+0000] {subprocess.py:93} INFO - Completed 55.1 KiB/55.1 KiB (193.6 KiB/s) with 1 file(s) remainingmove: ../../home/ubuntu/response_data_28062024001046.json to s3://zillow-etl-bucket/response_data_28062024001046.json
[2024-06-28T00:10:50.868+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-28T00:10:50.868+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T00:10:50.889+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=zillow_analytics_dag, task_id=tsk_load_to_s3, run_id=manual__2024-06-28T00:10:43.659885+00:00, execution_date=20240628T001043, start_date=20240628T001049, end_date=20240628T001050
[2024-06-28T00:10:50.942+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T00:10:50.962+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-28T00:10:50.968+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
